"""
Oriented Cayley-Dickson Tower Analysis
=======================================
Implements Apoth3osis's block-diagonal displacement method with full
tracking of the oriented sign structure (Möbius-canonical cocycle).

CD cocycle: e_a * e_b = ε(a,b) * e_{a⊕b}
Generated by (a,b)(c,d) = (ac - d̄b, da + bc̄), conjugation ē_j = -e_j (j>0)

Usage
-----
  python oriented_cd_tower.py                          # levels 4-8
  python oriented_cd_tower.py --max-level 12           # levels 4-12
  python oriented_cd_tower.py --single 11              # one level only
  python oriented_cd_tower.py --compat-rate            # 25% hypothesis test
  python oriented_cd_tower.py --compat-rate --max-level 14

Timing reference (approximate, single core)
  k=10  dim=1024   ~4s
  k=11  dim=2048   ~30s
  k=12  dim=4096   ~5min
  k=13  dim=8192   ~40min
  k=14  dim=16384  ~7h      ← practical 1-day ceiling
  k=15  dim=32768  ~50h
"""

import numpy as np
import argparse
import sys
import time
from collections import defaultdict


# ─────────────────────────────────────────────────────────────────────────────
# CD sign table (Möbius-canonical cocycle)
# ─────────────────────────────────────────────────────────────────────────────

def build_cd_signs(level: int) -> np.ndarray:
    """
    sign[a,b] = ε(a,b) where e_a * e_b = sign[a,b] * e_{a^b}.

    Recursive CD doubling (a,b)(c,d) = (ac - d̄b, da + bc̄):
      Case 1  a<h, b<h  →  ε_k(a,b)     = ε_{k-1}(a,b)
      Case 2  a<h, b≥h  →  ε_k(a,h+b')  = ε_{k-1}(b',a)
      Case 3  a≥h, b<h  →  ε_k(h+a',b)  = 1            if b=0
                                          = −ε_{k-1}(a',b) otherwise
      Case 4  a≥h, b≥h  →  ε_k(h+a',h+b') = −1         if b'=0
                                             = ε_{k-1}(b',a') otherwise
    Memory: (2^level)^2 bytes (int8). Fine up to k~14 (256 MB).
    """
    if level == 0:
        return np.array([[1]], dtype=np.int8)

    prev = build_cd_signs(level - 1)
    h = 1 << (level - 1)
    d = 1 << level
    s = np.zeros((d, d), dtype=np.int8)

    s[:h, :h] = prev               # Case 1
    s[:h, h:] = prev.T             # Case 2: s[a, h+b'] = prev[b', a]
    s[h:, 0]  = 1                  # Case 3, b=0
    s[h:, 1:h] = -prev[:, 1:h]    # Case 3, b>0
    s[h:, h]   = -1                # Case 4, b'=0
    s[h:, h+1:] = prev[1:, :].T   # Case 4, b'>0: s[h+a',h+b']=prev[b',a']

    return s


def verify_signs(sign: np.ndarray) -> bool:
    return bool(np.all(np.abs(sign) == 1))


# ─────────────────────────────────────────────────────────────────────────────
# Block analysis
# ─────────────────────────────────────────────────────────────────────────────

def analyze_block(delta: int, D: int, sign: np.ndarray) -> dict:
    """
    Displacement block δ: elements x_i = e_i + e_{D+i⊕δ}, i in [0,D).

    Compatibility x_i · x_k = 0 (i < k) requires:
      Cond1: sign[i,k] == −sign[D+k⊕δ, D+i⊕δ]
      Cond2: sign[D+k⊕δ, i] == −sign[D+i⊕δ, k]

    Oriented sign of a compatible edge: ε(i,k) = sign[i,k].
    """
    lower = np.arange(D)
    upper = D + (lower ^ delta)

    LL = sign[np.ix_(lower, lower)]
    UU = sign[np.ix_(upper, upper)]
    UL = sign[np.ix_(upper, lower)]

    cond1 = LL == -UU.T      # LL[i,k] == −UU[k,i]
    cond2 = UL.T == -UL      # UL[k,i] == −UL[i,k]
    mask  = np.triu(np.ones((D, D), dtype=bool), k=1)
    compat = cond1 & cond2 & mask

    n_pos = int(np.sum((LL > 0) & compat))
    n_neg = int(np.sum((LL < 0) & compat))

    return {
        'hamming_weight': bin(delta).count('1'),
        'n_pos':  n_pos,
        'n_neg':  n_neg,
        'n_total': n_pos + n_neg,
        'asymmetry': n_pos - n_neg,
    }


def analyze_level(level: int) -> dict:
    D    = 1 << (level - 1)
    sign = build_cd_signs(level)
    assert verify_signs(sign), f"Sign table corrupt at k={level}"

    by_weight = defaultdict(lambda: {
        'n_blocks': 0, 'n_pos': 0, 'n_neg': 0,
        'n_total': 0, 'total_asymmetry': 0
    })

    for delta in range(D):
        bd = analyze_block(delta, D, sign)
        w  = bd['hamming_weight']
        bw = by_weight[w]
        bw['n_blocks']         += 1
        bw['n_pos']            += bd['n_pos']
        bw['n_neg']            += bd['n_neg']
        bw['n_total']          += bd['n_total']
        bw['total_asymmetry']  += bd['asymmetry']

    return {'level': level, 'D': D, 'by_weight': dict(by_weight)}


# ─────────────────────────────────────────────────────────────────────────────
# Reports
# ─────────────────────────────────────────────────────────────────────────────

def report(min_level: int = 4, max_level: int = 8):
    print("=" * 72)
    print("ORIENTED CD TOWER — Sign structure within displacement blocks")
    print("=" * 72)
    print()
    print("  w=Hamming weight of δ | +edges: ε(i,k)=+1 | −edges: ε(i,k)=−1")
    print("  asymm = (+)−(−) | ratio = +edges/total (0.5 = symmetric)")
    print()

    accumulation = []

    for level in range(min_level, max_level + 1):
        N = level - 3
        d = 1 << level
        D = d >> 1
        t0 = time.time()
        print(f"─── Level k={level}  (dim={d}, D={D}, N={N}) ───", flush=True)
        data = analyze_level(level)
        elapsed = time.time() - t0
        bw = data['by_weight']

        print(f"  {'w':>3}  {'#blocks':>8}  {'+edges':>10}  {'−edges':>10}"
              f"  {'asymm':>10}  {'ratio':>7}")
        for w in sorted(bw.keys()):
            s = bw[w]
            ratio = s['n_pos'] / s['n_total'] if s['n_total'] else float('nan')
            print(f"  {w:>3}  {s['n_blocks']:>8}  {s['n_pos']:>10}  {s['n_neg']:>10}"
                  f"  {s['total_asymmetry']:>10}  {ratio:>7.4f}")

        if 2 in bw:
            s2  = bw[2]
            deg = (N+1)*(N+2)
            print(f"\n  ► w=2 (3D oscillator shell, expected deg={deg}): "
                  f"+={s2['n_pos']} −={s2['n_neg']} asymm={s2['total_asymmetry']}")
        if 1 in bw:
            s1   = bw[1]
            deg2 = 2*(N+1)
            print(f"  ► w=1 (2D oscillator shell, expected deg={deg2}): "
                  f"+={s1['n_pos']} −={s1['n_neg']} asymm={s1['total_asymmetry']}")

        print(f"  (computed in {elapsed:.1f}s)")
        print()

        a2 = bw.get(2, {}).get('total_asymmetry', 0)
        a1 = bw.get(1, {}).get('total_asymmetry', 0)
        accumulation.append((level, N, a2, a1))

    print("=" * 72)
    print("CROSS-LEVEL SIGN ASYMMETRY ACCUMULATION")
    print("=" * 72)
    print(f"\n  {'k':>3}  {'N':>3}  {'w2_asymm':>12}  {'w1_asymm':>12}"
          f"  {'cumul_w2':>14}  {'cumul_w1':>14}  {'ratio_w2/w1':>12}")
    c2 = c1 = 0
    for level, N, a2, a1 in accumulation:
        c2 += a2; c1 += a1
        rr = f"{a2/a1:.3f}" if a1 else "—"
        print(f"  {level:>3}  {N:>3}  {a2:>12}  {a1:>12}"
              f"  {c2:>14}  {c1:>14}  {rr:>12}")
    print()


def compat_rate_report(min_level: int = 4, max_level: int = 12):
    """Test whether within-block compatibility rate converges to 25%."""
    print("COMPATIBILITY RATE TEST  (25%% cancellation hypothesis)")
    print("Expected: 2 independent sign conditions → ~25%% of pairs compatible")
    print()
    print(f"  {'k':>3}  {'D':>6}  {'edges':>12}  {'pairs':>14}  {'rate':>8}  note")

    for level in range(min_level, max_level + 1):
        D    = 1 << (level - 1)
        sign = build_cd_signs(level)
        total_pairs = total_edges = 0
        for delta in range(D):
            bd = analyze_block(delta, D, sign)
            total_pairs += D * (D - 1) // 2
            total_edges += bd['n_total']
        rate = total_edges / total_pairs if total_pairs else 0
        note = "<── converging" if abs(rate - 0.25) < 0.01 else ""
        print(f"  {level:>3}  {D:>6}  {total_edges:>12}  {total_pairs:>14}"
              f"  {rate:>8.4f}  {note}")
    print()
    print("Interpretation: if rate → 0.25, the 25% settled sum in the")
    print("heritage fill is the population statistic of the 4-term")
    print("cancellation requiring two independent sign conditions.")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point — single clean main block
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--min-level', type=int, default=4)
    p.add_argument('--max-level', type=int, default=8,
                   help='k=14 ≈ 7h, k=15 > 2 days')
    p.add_argument('--single',    type=int, default=None,
                   help='Analyse a single level and exit')
    p.add_argument('--compat-rate', action='store_true',
                   help='Run 25%% compatibility rate test instead of full report')
    args = p.parse_args()

    if args.single is not None:
        report(min_level=args.single, max_level=args.single)
    elif args.compat_rate:
        compat_rate_report(min_level=args.min_level, max_level=args.max_level)
    else:
        report(min_level=args.min_level, max_level=args.max_level)
